title: AppointmentTypes
modelClass: RomainMazB\Appointment\Models\AppointmentType
list: $/romainmazb/appointment/models/appointmenttype/columns.yaml
recordUrl: 'romainmazb/appointment/appointmenttypes/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
