list: $/romainmazb/appointment/models/holidays/columns.yaml
modelClass: RomainMazB\Appointment\Models\Holidays
title: Holidays
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'romainmazb/appointment/holidays/update/:id'
